apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  selector:
    matchLabels:
      app: deployment1
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      serviceAccountName: microservice-sa
      containers:
      - name: deployment1
        image: nginx:latest
