apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-secret-app
spec:
  selector:
    matchLabels:
      app: no-secret-app
  template:
    metadata:
      labels:
        app: no-secret-app
    spec:
      serviceAccountName: no-secret-sa
      containers:
      - name: no-secret-app
        image: nginx:latest
