# backend.yml, part II, clusterIP

---
apiVersion: v1
kind: Service
metadata:
  namespace: titanic
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
