apiVersion: v1
kind: Service
metadata:
  name: frontend-alb
  namespace: titanic
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
