apiVersion: v1
kind: PersistentVolume
metadata:
  name: titanic-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /d/Vamsi/3-Tech-Projects/Kubernetes/27-titanic/data 
  persistentVolumeReclaimPolicy: Retain
