apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: titanic-data-pvc
  namespace: titanic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: titanic-data-pv
  storageClassName: ""
