apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: OnFailure
  initContainers:
  - name: sc1
    restartPolicy: Always
    image: alpine:3
    command: ["sh", "-c", "echo 'Its a beautiful day. SO SIMLE' > /app/config.txt"]
    #command: [ "sh", "-c", "sleep 240" ]    
  containers:
  - name: rc1
    image: alpine:3
    command: [ "sh", "-c", "sleep 300" ]
    startupProbe:
      exec:
        command: ["/bin/sh", "-c", "sleep 5"]
      initialDelaySeconds: 0
      periodSeconds: 30
      timeoutSeconds: 999
    readinessProbe:
      exec:
        command: ["/bin/sh", "-c", "sleep 5"]
      initialDelaySeconds: 0
      periodSeconds: 30
      timeoutSeconds: 999
