apiVersion: apps/v1
kind: Deployment
metadata:
  name: delayed-http-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: delayed-http
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: delayed-http
    spec:
      containers:
      - name: delayed-http
        image: deminy/delayed-http-response:latest
        ports:
        - containerPort: 80
        # Optional: readinessProbe to ensure pod is ready before serving traffic
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
